frontend_image: ghcr.io/leylahosseini/frontend-dev:a4a6d634e64bafa325b668212b6bc18a467352df
backend_image:  ghcr.io/leylahosseini/backend-dev:a4a6d634e64bafa325b668212b6bc18a467352df
#database_image: enginedevops/database-dev:a4a6d634e64bafa325b668212b6bc18a467352df
NAME_DB: mongo
NAME_DB_SVC: mongo-dev
MONGO_USER: admin
MONGO_PASS: admin123
Replica: 1
PORT_Frontend: 5000
Name_Frontend: frontend
Name_Backend: backend
