frontend_image: enginedevops/frontend_prod:e0f6da77756c5ed2d03452484dc570a79c19f0d2
backend_image: enginedevops/backend_prod:e0f6da77756c5ed2d03452484dc570a79c19f0d2
#database_image: enginedevops/database_dev:e0f6da77756c5ed2d03452484dc570a79c19f0d2
NAME_DB_DEP: mongo-prod
NAME_DB_SVC: mongo-prod      
#MONGO_USER: admin
#MONGO_PASS: admin123
Replica: 1
#PORT_Frontend: 5000
FRONTEND_NAME: frontend
FRONTEND_PORT: 5000
FRONTEND_DOMAIN: frontend.enginedevops.ir
DB_HOST: mongo-prod
DB_USERNAME: admin
DB_PASSWORD: admin123
DB_NAME: fake-store
DB_PORT: 27017
DATABASE_URL: mongodb://admin:admin123@mongo-prod:27017/fake-store?authSource=admin
BACKEND_NAME: backend
