apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.Name_DB }}
  labels:
    app: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
          image: mongo
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: {{ .Values.DB_USER }}
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: {{ .Values.DB_PASS }}
          ports:
          - containerPort: 27017

