
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: {{ .Values.NAME_DB }}
  labels:
    app: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: {{ .Values.DB_USER }}
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: {{ .Values.DB_PASS }}
        ports:
        - containerPort: 27017
          name: mongo
