apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.Name_Backend}}
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
          image: nginx
          ports:
          - containerPort: 80
