apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.Name_frontend }}
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: {{ .Values.Replica }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
       —name: frontend
          image: frontend
          ports:
           —containerPort: 8000
