apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.FRONTEND_NAME }}
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.FRONTEND_PORT }}
#      targetPort: 3000
  type: ClusterIP

