apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Name_Frontend }}
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.PORT }}
#      targetPort: 3000
  type: ClusterIP

